services:
  backend:
    image: node:20
    container_name: backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '4000:4000'
    environment:
      - DB_USER=${DB_USER}             # Make sure to set these in your .env file
      - DB_HOST=host.docker.internal    # Use host.docker.internal to point to local PostgreSQL
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}  
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - TYPESENSE_HOST=http://typesense:8108
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    depends_on:
      - minio
      - typesense
    command: bash -c "npm install && npm start"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"  # For the MinIO API
      - "9001:9001" 
    command: server --console-address ":9001" /data

  typesense:
    image: typesense/typesense:0.24.0
    container_name: typesense
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
    volumes:
      - typesense-data:/data
    ports:
      - '8108:8108'
    command: typesense-server --data-dir /data --api-key=${TYPESENSE_API_KEY}

volumes:
  minio-data:
  typesense-data:
